# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18250025163e44a6a2b8c49d32f68fb95e829ef09f7177a6fc25aedb9f11dad3d35ee4a3651585d581f092987b05bdb414a71605cdf5cd055901da50e1b9ee78

test:
  secret_key_base: e4177c0bdccfc446b351caeb5b8e574239ad1634d1d243766384806ad0379cf860510fbd72493d01c46a5fba98329bd444148a215f11b67d0f1d83c8439b445b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
